name: Setup python environment
description: Install and configure caching for Python environment
runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"
        cache: pip

    - name: Install uv
      shell: bash
      run: |
        pipx install uv

    - name: Install dependencies
      shell: bash
      run: |
        uv sync